site_name: CS0200 Handouts
site_url: https://brown-csci0200.github.io/cs0200_handouts/
site_author: CS0200 Staff
site_description: Handouts for CS0200 (Brown University) are hosted here!

docs_dir: docs
